CREATE TABLE "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar NOT NULL,
    "email" varchar UNIQUE NOT NULL,
    "password_hash" varchar NOT NULL,
    "role" varchar NOT NULL,
    "cpf" varchar(11) UNIQUE,
    "birth_date" date,
    "phone" varchar(20),
    "address" varchar,
    "active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT chk_user_role
    CHECK (role IN ('admin', 'patient', 'caregiver'))
);

CREATE TABLE "patients" (
    "user_id" integer PRIMARY KEY
);

CREATE TABLE "caregivers" (
    "user_id" integer PRIMARY KEY
);

CREATE TABLE "caregiver_patient_links" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "patient_id" integer NOT NULL,
    "caregiver_id" integer NOT NULL,
    "created_date" date NOT NULL,
    "created_time" time NOT NULL,
    "active" boolean NOT NULL DEFAULT true,

    CONSTRAINT uq_caregiver_patient
      UNIQUE ("patient_id", "caregiver_id")
);

CREATE TABLE "caregiver_patient_link_history" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "link_id" integer NOT NULL,
    "started_date" date NOT NULL,
    "started_time" time NOT NULL,
    "ended_date" date,
    "ended_time" time
);

CREATE TABLE "medicines" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "patient_id" integer NOT NULL,
    "name" varchar NOT NULL,
    "dosage" varchar NOT NULL,
    "schedule_time" time,
    "notes" text,
    "active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "daily_reports" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "link_id" INTEGER NOT NULL,
    "created_by_user_id" INTEGER NOT NULL,
    "hygiene" text,
    "food" text,
    "blood_pressure" varchar,
    "glucose" varchar,
    "temperature" varchar,
    "observations" text,
    "report_date" date NOT NULL,
    "report_time" time NOT NULL,
    "active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_daily_report_link
    FOREIGN KEY ("link_id")
      REFERENCES "caregiver_patient_links"("id"),

  CONSTRAINT fk_daily_report_created_by
    FOREIGN KEY ("created_by_user_id")
      REFERENCES "users"("id")
);

CREATE TABLE "medicine_administrations" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "medicine_id" integer NOT NULL,
    "link_id" integer NOT NULL,
    "created_by_user_id" INTEGER NOT NULL,
    "dosage_given" varchar,
    "notes" text,
    "administration_date" date NOT NULL,
    "administration_time" time NOT NULL,
    "active" boolean NOT NULL DEFAULT true,
    "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_medicine_administrations_medicines
    FOREIGN KEY ("medicine_id")
      REFERENCES  "medicines"("id"),

  CONSTRAINT fk_medicine_administrations_link
    FOREIGN KEY ("link_id")
      REFERENCES  "caregiver_patient_links"("id"),
  
  CONSTRAINT fk_medicine_administrations_created_by
    FOREIGN KEY ("created_by_user_id")
      REFERENCES "users"("id")

);

ALTER TABLE "patients"
ADD CONSTRAINT fk_patients_user
FOREIGN KEY ("user_id")
REFERENCES "users" ("id");

ALTER TABLE "caregivers"
ADD CONSTRAINT fk_caregivers_user
FOREIGN KEY ("user_id")
REFERENCES "users" ("id");

ALTER TABLE "caregiver_patient_links"
ADD CONSTRAINT fk_link_patient
FOREIGN KEY ("patient_id")
REFERENCES "patients" ("user_id");

ALTER TABLE "caregiver_patient_links"
ADD CONSTRAINT fk_link_caregiver
FOREIGN KEY ("caregiver_id")
REFERENCES "caregivers" ("user_id");

ALTER TABLE "caregiver_patient_link_history"
ADD CONSTRAINT fk_link_history
FOREIGN KEY ("link_id")
REFERENCES "caregiver_patient_links" ("id");

ALTER TABLE "medicines"
ADD CONSTRAINT fk_medicines_patient
FOREIGN KEY ("patient_id")
REFERENCES "patients" ("user_id");


